use customer_behaviour;
show tables;

-- query to show first 5 rows of the table
SELECT * 
FROM customer_data
LIMIT 10;

-- Q1. What is the total revenue generated by male vs. female customers?
SELECT gender, Sum(purchase_amount) AS revenue
FROM customer_data
GROUP BY gender;

-- Q2. Which customers used a discount but still spent more than the average purchase amount? 
SELECT customer_id, purchase_amount, discount_applied
FROM customer_data
WHERE 
	discount_applied = 'Yes' 
    AND 
    purchase_amount >= (SELECT AVG(purchase_amount) FROM customer_data);

-- Q3. Which are the top 5 products with the highest average review rating?
SELECT item_purchased, ROUND(AVG(review_rating),2) AS "average product rating"
FROM customer_data
GROUP BY item_purchased
ORDER BY AVG(review_rating) DESC
LIMIT 5;

-- Q4. Compare the average Purchase Amounts between Standard and Express Shipping. 
SELECT shipping_type, ROUND(AVG(purchase_amount),2) AS "avg purchase amount"
FROM customer_data
WHERE shipping_type IN ('Standard','Express')
GROUP BY shipping_type;

-- Q5. Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers.
SELECT subscription_status,
COUNT(customer_id) AS "total_customers",
ROUND(AVG(purchase_amount),2) AS "avg_spend",
ROUND(SUM(purchase_amount),2) AS "total_revenue"
FROM customer_data
GROUP BY subscription_status
ORDER BY total_revenue, avg_spend DESC;

-- Q6. Which 5 products have the highest percentage of purchases with discounts applied?
SELECT item_purchased, 
 ROUND(COUNT(CASE WHEN discount_applied ='Yes' THEN 1 END)* 100.0/COUNT(*),2) AS discount_percentage
FROM customer_data
GROUP BY item_purchased
ORDER BY discount_percentage DESC
LIMIT 5;

-- this means which product rely heavily on discount (eg. hat if sold 10 times, 50% times, that is 5 times it was sold with a discount)

-- Q7. Segment customers into New, Returning, and Loyal based on their total number of previous purchases, and show the count of each segment. 
SELECT CASE 
	WHEN previous_purchases = 1 THEN 'NEW'
    WHEN previous_purchases BETWEEN 2 AND 10 THEN 'RETURNING'
    ELSE 'LOYAL'
    END AS customer_segment,
    COUNT(*) AS customer_count
FROM customer_data
GROUP BY customer_segment
ORDER BY customer_count DESC;

-- Q8. What are the top 3 most purchased products within each category? 
WITH item_counts AS (
    SELECT 
        category,
        item_purchased,
        COUNT(customer_id) AS total_orders,
        ROW_NUMBER() OVER (
            PARTITION BY category
            ORDER BY COUNT(customer_id) DESC
        ) AS item_rank
    FROM customer_data
    GROUP BY category, item_purchased
)
SELECT 
    item_rank,
    category,
    item_purchased,
    total_orders
FROM item_counts
WHERE item_rank <= 3;

-- Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
SELECT subscription_status,
COUNT(customer_id) AS repeat_buyers
FROM customer_data
WHERE previous_purchases >5
GROUP BY subscription_status;

-- Q10. What is the revenue contribution of each age group? 
SELECT age_group,
SUM(purchase_amount) AS total_revenue
FROM customer_data
GROUP BY age_group
ORDER BY total_revenue DESC;
